package:
  name: pvapy
  version: 2.0.1

source:
  git_rev: 2.0.1
  git_url: https://github.com/epics-base/pvaPy

build:
  number: 1
  script_env:
    - BUILD_FLAGS

test:
  requires:
    - nose

  source_files:
    - test

requirements:
  build:
    - python
    - sphinx
    - sphinx_rtd_theme
    - numpy>1.15
    - epics-base=7.0.3.1
    - pvapy-boost=1.70.0

  run:
    - python
    - numpy>1.15
    - epics-base=7.0.3.1
    - pvapy-boost=1.70.0

about:
  home: https://github.com/epics-base/pvaPy
  license: EPICS Open License
  summary: Python library for EPICS PV Access 



