package:
  name: pvapy
  version: 1.1.0.rc1

source:
  git_rev: master
  git_url: https://github.com/epics-base/pvaPy

build:
  number: 1

requirements:
  build:
    - pvapy-epics
    - python
    - numpy 
    - pvapy-boost

  run:
    - pvapy-epics
    - python
    - numpy 
    - pvapy-boost

about:
  home: https://github.com/epics-base/pvaPy
  license: EPICS Open License

