package:
  name: pvapy
  version: 1.5.0

source:
  git_rev: master
  git_url: https://github.com/epics-base/pvaPy

build:
  number: 1
  script_env:
    - BUILD_FLAGS

requirements:
  build:
    - python
    - sphinx
    - sphinx_rtd_theme
    - numpy>1.15
    - epics-base=7.0.2.2
    - pvapy-boost=1.70.0

  run:
    - python
    - numpy>1.15
    - epics-base=7.0.2.2
    - pvapy-boost=1.70.0

about:
  home: https://github.com/epics-base/pvaPy
  license: EPICS Open License
  summary: Python library for EPICS PV Access 



