package:
  name: pvapy
  version: 2.0.0

source:
  path: ../../..

build:
  number: 1
  script_env:
    - BUILD_FLAGS

test:
  requires:
    - nose

  source_files:
    - test

# Python build version requirement is temporary due to bug in conda's
# 3.7.4 build which results in the following behavior:
# bluegill2> python
# Python 3.7.4 (default, Aug  9 2019, 18:51:30)
# [GCC 7.3.0] :: Anaconda, Inc. on linux
# Type "help", "copyright", "credits" or "license" for more information.
# >>> from distutils.sysconfig import *
# >>> get_config_var('VERSION')
# 4.8.5-39)
# '3.7'

requirements:
  build:
    - python<=3.7.3
    - sphinx
    - sphinx_rtd_theme
    - numpy>1.15
    - epics-base=7.0.3
    - pvapy-boost=1.70.0

  run:
    - python
    - numpy>1.15
    - epics-base=7.0.3
    - pvapy-boost=1.70.0

about:
  home: https://github.com/epics-base/pvaPy
  license: EPICS Open License
  summary: Python library for EPICS PV Access 



